name: GEO
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - boto3
  - cartopy
  - datashader
  - descartes
  - folium
  - geojson
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - ipyleaflet
  - jupyter
  - osmnx
  - pandas
  - pygeos
  - rasterio
  - sat-search
  - shapely
  - toolz
  - utm
